[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "zero-jax"
version = "0.4.30"
description = "Zero-dependency pure Python implementation of the JAX API surface."
authors = [{ name = "Samuel Marks" }]
requires-python = ">=3.9"
dynamic = ["dependencies", "optional-dependencies"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
test = ["requirements-test.txt"]

[tool.coverage.run]
omit = [
    "fix_docs.py",
    "fix_indent.py",
    "generate_jnp_stubs.py",
    "scripts/*"
]

[tool.ruff.lint]
ignore = ['E402', 'F401', 'F841', 'E741', 'E501', 'RUF059', 'BLE001', 'S110', 'C414', 'SIM102', 'FURB136', 'PLE0605', 'UP035', 'UP006', 'B004', 'FA100', 'UP045', 'UP007', 'UP031', 'RUF013', 'SIM101']

[tool.pytest.ini_options]
addopts = "--strict-markers"
markers = [
    "reference: Tests comparing zero-jax to official jax output.",
]

[tool.hatch.metadata]
allow-direct-references = true
