"""Mock implementation for xla_client alias."""

from zero_jax.lib.xla_client import (
    DTYPE_TO_XLA_ELEMENT_TYPE,
    Union,
    XLA_ELEMENT_TYPE_TO_DTYPE,
    annotations,
    array_result_handler,
)
from zero_jax.lib.xla_client import (
    batched_block_until_ready,
    batched_copy_array_to_devices_with_sharding,
    batched_device_put,
    check_and_canonicalize_memory_kind,
    custom_call_targets,
)
from zero_jax.lib.xla_client import (
    encode_inspect_sharding_callback,
    get_topology_for_devices,
    logger,
    mlir_api_version,
    register_custom_call_partitioner,
)
from zero_jax.lib.xla_client import (
    weakref_lru_cache,
    xla_platform_names,
    ArrayImpl,
    Client,
    CompileOptions,
)
from zero_jax.lib.xla_client import (
    ConvolutionDimensionNumbers,
    CustomCallHandler,
    CustomCallTargetTraits,
    Device,
    DeviceAssignment,
)
from zero_jax.lib.xla_client import (
    DeviceList,
    DeviceTopology,
    DotDimensionNumbers,
    FftType,
    Frame,
)
from zero_jax.lib.xla_client import (
    GSPMDSharding,
    GatherDimensionNumbers,
    HloSharding,
    HostBufferSemantics,
    Layout,
)
from zero_jax.lib.xla_client import (
    LoadedExecutable,
    Mapping,
    Memory,
    NamedSharding,
    OpMetadata,
)
from zero_jax.lib.xla_client import (
    OpSharding,
    PaddingConfig,
    PaddingConfigDimension,
    PaddingType,
    PjRtLayout,
)
from zero_jax.lib.xla_client import (
    PmapSharding,
    PrecisionConfig,
    PrimitiveType,
    ProgramShape,
    Protocol,
)
from zero_jax.lib.xla_client import (
    ReplicaGroup,
    ScatterDimensionNumbers,
    Sequence,
    Shape,
    ShapeIndex,
)
from zero_jax.lib.xla_client import (
    Sharding,
    SingleDeviceSharding,
    Traceback,
    XlaBuilder,
    XlaComputation,
)
from zero_jax.lib.xla_client import (
    XlaOp,
    XlaRuntimeError,
    bfloat16,
    float8_e4m3b11fnuz,
    float8_e4m3fn,
)
from zero_jax.lib.xla_client import (
    float8_e4m3fnuz,
    float8_e5m2,
    float8_e5m2fnuz,
    CurrentSourceInfoMetadata,
    LoadedExecutable_execute,
)
from zero_jax.lib.xla_client import (
    LoadedExecutable_execute_with_token,
    dtype_to_etype,
    execute_with_python_values,
    execute_with_python_values_replicated,
    generate_pjrt_gpu_plugin_options,
)
from zero_jax.lib.xla_client import (
    heap_profile,
    initialize_pjrt_plugin,
    load_pjrt_plugin_dynamically,
    load_pjrt_plugin_with_c_api,
    make_c_api_client,
)
from zero_jax.lib.xla_client import (
    make_c_api_device_topology,
    make_convolution_dimension_numbers,
    make_cpu_client,
    make_dot_dimension_numbers,
    make_gpu_client,
)
from zero_jax.lib.xla_client import (
    make_padding_config,
    make_replica_groups,
    make_tfrt_tpu_c_api_client,
    make_tfrt_tpu_c_api_device_topology,
    make_tpu_client,
)
from zero_jax.lib.xla_client import (
    pjrt_plugin_initialized,
    pjrt_plugin_loaded,
    register_custom_call_handler,
    register_custom_call_target,
    shape_from_pyval,
)
from zero_jax.lib.xla_client import (
    tracebacks,
    window_padding_type_to_pad_values,
    atexit,
    contextlib,
    enum,
)
from zero_jax.lib.xla_client import (
    gzip,
    hlo_sharding_util,
    ifrt_programs,
    inspect,
    logging,
)
from zero_jax.lib.xla_client import ml_dtypes, np, ops, os, profiler
from zero_jax.lib.xla_client import threading

__all__ = [
    "DTYPE_TO_XLA_ELEMENT_TYPE",
    "Union",
    "XLA_ELEMENT_TYPE_TO_DTYPE",
    "annotations",
    "array_result_handler",
    "batched_block_until_ready",
    "batched_copy_array_to_devices_with_sharding",
    "batched_device_put",
    "check_and_canonicalize_memory_kind",
    "custom_call_targets",
    "encode_inspect_sharding_callback",
    "get_topology_for_devices",
    "logger",
    "mlir_api_version",
    "register_custom_call_partitioner",
    "weakref_lru_cache",
    "xla_platform_names",
    "ArrayImpl",
    "Client",
    "CompileOptions",
    "ConvolutionDimensionNumbers",
    "CustomCallHandler",
    "CustomCallTargetTraits",
    "Device",
    "DeviceAssignment",
    "DeviceList",
    "DeviceTopology",
    "DotDimensionNumbers",
    "FftType",
    "Frame",
    "GSPMDSharding",
    "GatherDimensionNumbers",
    "HloSharding",
    "HostBufferSemantics",
    "Layout",
    "LoadedExecutable",
    "Mapping",
    "Memory",
    "NamedSharding",
    "OpMetadata",
    "OpSharding",
    "PaddingConfig",
    "PaddingConfigDimension",
    "PaddingType",
    "PjRtLayout",
    "PmapSharding",
    "PrecisionConfig",
    "PrimitiveType",
    "ProgramShape",
    "Protocol",
    "ReplicaGroup",
    "ScatterDimensionNumbers",
    "Sequence",
    "Shape",
    "ShapeIndex",
    "Sharding",
    "SingleDeviceSharding",
    "Traceback",
    "XlaBuilder",
    "XlaComputation",
    "XlaOp",
    "XlaRuntimeError",
    "bfloat16",
    "float8_e4m3b11fnuz",
    "float8_e4m3fn",
    "float8_e4m3fnuz",
    "float8_e5m2",
    "float8_e5m2fnuz",
    "CurrentSourceInfoMetadata",
    "LoadedExecutable_execute",
    "LoadedExecutable_execute_with_token",
    "dtype_to_etype",
    "execute_with_python_values",
    "execute_with_python_values_replicated",
    "generate_pjrt_gpu_plugin_options",
    "heap_profile",
    "initialize_pjrt_plugin",
    "load_pjrt_plugin_dynamically",
    "load_pjrt_plugin_with_c_api",
    "make_c_api_client",
    "make_c_api_device_topology",
    "make_convolution_dimension_numbers",
    "make_cpu_client",
    "make_dot_dimension_numbers",
    "make_gpu_client",
    "make_padding_config",
    "make_replica_groups",
    "make_tfrt_tpu_c_api_client",
    "make_tfrt_tpu_c_api_device_topology",
    "make_tpu_client",
    "pjrt_plugin_initialized",
    "pjrt_plugin_loaded",
    "register_custom_call_handler",
    "register_custom_call_target",
    "shape_from_pyval",
    "tracebacks",
    "window_padding_type_to_pad_values",
    "atexit",
    "contextlib",
    "enum",
    "gzip",
    "hlo_sharding_util",
    "ifrt_programs",
    "inspect",
    "logging",
    "ml_dtypes",
    "np",
    "ops",
    "os",
    "profiler",
    "threading",
]
